#!/bin/sh

[ -e /etc/config/hostname-setup ] && exit 0
touch /etc/config/hostname-setup

. /lib/functions.sh

model="$(board_name | sed 's/^[^,]*,//' | tr 'a-z' 'A-Z')"
suffix="$(cat /sys/class/ieee80211/phy0/macaddress 2>/dev/null | tr -d ':' | tail -c 4 | tr 'A-Z' 'a-z')"
[ -n "$model" ] && [ -n "$suffix" ] || exit 0
name="$model-$suffix"

uci set system.@system[0].hostname="$name"
uci commit system
echo "$name" > /proc/sys/kernel/hostname

exit 0
