firmware_targets:
  - id: cudy-tr3000-v1
    model: cudy-tr3000
    variant: default
    target: mediatek
    subtarget: filogic
    profile: cudy_tr3000-v1

  - id: gl-ar300m-nand
    model: gl-ar300m
    variant: nand
    target: ath79
    subtarget: nand
    profile: glinet_gl-ar300m-nand

  - id: gl-ar300m-nor
    model: gl-ar300m
    variant: nor
    target: ath79
    subtarget: nand
    profile: glinet_gl-ar300m-nor

  - id: gl-ar750s-nor
    model: gl-ar750s
    variant: nor
    target: ath79
    subtarget: nand
    profile: glinet_gl-ar750s-nor

  - id: gl-ar750s-nor-nand
    model: gl-ar750s
    variant: nor-nand
    target: ath79
    subtarget: nand
    profile: glinet_gl-ar750s-nor-nand

  - id: gl-microuter-n300
    model: gl-microuter-n300
    variant: default
    target: ramips
    subtarget: mt76x8
    profile: glinet_microuter-n300

  - id: gl-mt300n-v2
    model: gl-mt300n-v2
    variant: default
    target: ramips
    subtarget: mt76x8
    profile: glinet_gl-mt300n-v2
